// <auto-generated />
using System;
using CarTroubleSolver.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

#nullable disable

namespace CarTroubleSolver.Shared.Migrations
{
    [DbContext(typeof(CarTroubleSolverDbContext))]
    [Migration("20241108120851_ratedate")]
    partial class ratedate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarTroubleSolver.Shared.Models.ExtraModels.Accident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProblemDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Service")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WorkshopId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("WorkshopId");

                    b.ToTable("Accidents");
                });

            modelBuilder.Entity("CarTroubleSolver.Shared.Models.ExtraModels.HistoryItems", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<Guid>("RepairHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RepairHistoryId");

                    b.ToTable("HistoryItems");
                });

            modelBuilder.Entity("CarTroubleSolver.Shared.Models.ExtraModels.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfVisit")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<Guid?>("PreviousMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("RateMessage")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ReceiverUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReceiverWorkshopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Responsed")
                        .HasColumnType("bit");

                    b.Property<Guid?>("SenderUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SenderWorkshopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Service")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("PreviousMessageId");

                    b.HasIndex("ReceiverUserId");

                    b.HasIndex("ReceiverWorkshopId");

                    b.HasIndex("SenderUserId");

                    b.HasIndex("SenderWorkshopId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("CarTroubleSolver.Shared.Models.ExtraModels.RepairHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccidentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Service")
                        .HasColumnType("int");

                    b.Property<float>("SpentHours")
                        .HasColumnType("real");

                    b.Property<Guid>("WorkshopId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccidentId")
                        .IsUnique();

                    b.HasIndex("CarId");

                    b.HasIndex("WorkshopId");

                    b.ToTable("RepairHistory");
                });

            modelBuilder.Entity("CarTroubleSolver.Shared.Models.ExtraModels.StatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccidentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ControlQueue")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccidentId");

                    b.ToTable("StatusHistory");
                });

            modelBuilder.Entity("CarTroubleSolver.Shared.Models.UserPanel.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Brand")
                        .HasColumnType("int");

                    b.Property<int>("CarType")
                        .HasColumnType("int");

                    b.Property<Guid>("ColorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfProduction")
                        .HasColumnType("date");

                    b.Property<int>("DoorCount")
                        .HasColumnType("int");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Mileage")
                        .HasColumnType("bigint");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("CarTroubleSolver.Shared.Models.UserPanel.CarColor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Blue")
                        .HasColumnType("int");

                    b.Property<int>("Green")
                        .HasColumnType("int");

                    b.Property<int>("Red")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CarColor");
                });

            modelBuilder.Entity("CarTroubleSolver.Shared.Models.UserPanel.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000000"),
                            Name = "BasicUser"
                        },
                        new
                        {
                            Id = new Guid("00000002-0000-0000-0000-000000000000"),
                            Name = "Mechanic"
                        },
                        new
                        {
                            Id = new Guid("00000003-0000-0000-0000-000000000000"),
                            Name = "MechanicalWorkshop"
                        },
                        new
                        {
                            Id = new Guid("00000004-0000-0000-0000-000000000000"),
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("CarTroubleSolver.Shared.Models.UserPanel.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("00000001-0000-0000-0000-000000000000"));

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CarTroubleSolver.Shared.Models.WorkshopPanel.HourConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("From")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("To")
                        .HasColumnType("time");

                    b.Property<Guid>("WorkshopId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkshopId");

                    b.ToTable("Hours");
                });

            modelBuilder.Entity("CarTroubleSolver.Shared.Models.WorkshopPanel.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkshopId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkshopId");

                    b.ToTable("Rating");
                });

            modelBuilder.Entity("CarTroubleSolver.Shared.Models.WorkshopPanel.Workshop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography");

                    b.Property<long>("NIP")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Workshops");
                });

            modelBuilder.Entity("CarTroubleSolver.Shared.Models.WorkshopPanel.WorkshopServices", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Service")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkshopId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkshopId");

                    b.ToTable("WorkshopServices");
                });

            modelBuilder.Entity("CarTroubleSolver.Shared.Models.ExtraModels.Accident", b =>
                {
                    b.HasOne("CarTroubleSolver.Shared.Models.UserPanel.Car", "Car")
                        .WithMany("Accidents")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarTroubleSolver.Shared.Models.WorkshopPanel.Workshop", "Workshop")
                        .WithMany("Accidents")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("CarTroubleSolver.Shared.Models.ExtraModels.HistoryItems", b =>
                {
                    b.HasOne("CarTroubleSolver.Shared.Models.ExtraModels.RepairHistory", "RepairHistory")
                        .WithMany("HistoryItems")
                        .HasForeignKey("RepairHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RepairHistory");
                });

            modelBuilder.Entity("CarTroubleSolver.Shared.Models.ExtraModels.Message", b =>
                {
                    b.HasOne("CarTroubleSolver.Shared.Models.UserPanel.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId");

                    b.HasOne("CarTroubleSolver.Shared.Models.ExtraModels.Message", "PreviousMessage")
                        .WithMany()
                        .HasForeignKey("PreviousMessageId");

                    b.HasOne("CarTroubleSolver.Shared.Models.UserPanel.User", "ReceiverUser")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("ReceiverUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CarTroubleSolver.Shared.Models.WorkshopPanel.Workshop", "ReceiverWorkshop")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("ReceiverWorkshopId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CarTroubleSolver.Shared.Models.UserPanel.User", "SenderUser")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CarTroubleSolver.Shared.Models.WorkshopPanel.Workshop", "SenderWorkshop")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderWorkshopId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Car");

                    b.Navigation("PreviousMessage");

                    b.Navigation("ReceiverUser");

                    b.Navigation("ReceiverWorkshop");

                    b.Navigation("SenderUser");

                    b.Navigation("SenderWorkshop");
                });

            modelBuilder.Entity("CarTroubleSolver.Shared.Models.ExtraModels.RepairHistory", b =>
                {
                    b.HasOne("CarTroubleSolver.Shared.Models.ExtraModels.Accident", "Accident")
                        .WithOne("RepairHistory")
                        .HasForeignKey("CarTroubleSolver.Shared.Models.ExtraModels.RepairHistory", "AccidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarTroubleSolver.Shared.Models.UserPanel.Car", "Car")
                        .WithMany("RepairHistory")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CarTroubleSolver.Shared.Models.WorkshopPanel.Workshop", "Workshop")
                        .WithMany("RepairHistory")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Accident");

                    b.Navigation("Car");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("CarTroubleSolver.Shared.Models.ExtraModels.StatusHistory", b =>
                {
                    b.HasOne("CarTroubleSolver.Shared.Models.ExtraModels.Accident", "Accident")
                        .WithMany("StatusHistory")
                        .HasForeignKey("AccidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accident");
                });

            modelBuilder.Entity("CarTroubleSolver.Shared.Models.UserPanel.Car", b =>
                {
                    b.HasOne("CarTroubleSolver.Shared.Models.UserPanel.CarColor", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarTroubleSolver.Shared.Models.UserPanel.User", "Owner")
                        .WithMany("Cars")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("CarTroubleSolver.Shared.Models.UserPanel.User", b =>
                {
                    b.HasOne("CarTroubleSolver.Shared.Models.UserPanel.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CarTroubleSolver.Shared.Models.WorkshopPanel.HourConfiguration", b =>
                {
                    b.HasOne("CarTroubleSolver.Shared.Models.WorkshopPanel.Workshop", "Workshop")
                        .WithMany("OpenHours")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("CarTroubleSolver.Shared.Models.WorkshopPanel.Rating", b =>
                {
                    b.HasOne("CarTroubleSolver.Shared.Models.UserPanel.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarTroubleSolver.Shared.Models.WorkshopPanel.Workshop", "Workshop")
                        .WithMany("Ratings")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("CarTroubleSolver.Shared.Models.WorkshopPanel.WorkshopServices", b =>
                {
                    b.HasOne("CarTroubleSolver.Shared.Models.WorkshopPanel.Workshop", "Workshop")
                        .WithMany("Services")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("CarTroubleSolver.Shared.Models.ExtraModels.Accident", b =>
                {
                    b.Navigation("RepairHistory")
                        .IsRequired();

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("CarTroubleSolver.Shared.Models.ExtraModels.RepairHistory", b =>
                {
                    b.Navigation("HistoryItems");
                });

            modelBuilder.Entity("CarTroubleSolver.Shared.Models.UserPanel.Car", b =>
                {
                    b.Navigation("Accidents");

                    b.Navigation("RepairHistory");
                });

            modelBuilder.Entity("CarTroubleSolver.Shared.Models.UserPanel.User", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("Ratings");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("SentMessages");
                });

            modelBuilder.Entity("CarTroubleSolver.Shared.Models.WorkshopPanel.Workshop", b =>
                {
                    b.Navigation("Accidents");

                    b.Navigation("OpenHours");

                    b.Navigation("Ratings");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("RepairHistory");

                    b.Navigation("SentMessages");

                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
